name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 11"

    steps:
      - uses: actions/checkout@v2
      - name: Build platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme tree-sitter-xcframework -destination "${{ matrix.destination }}" build | xcpretty
